version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=db
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Проброс портов (внешний:внутренний)
    networks:
      - net
  app:  
    image: bdbd
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app

    networks:
      - net

    
  

  test_app:  
    image: bdbd
    build: .
    volumes:
      - ./:/app
    entrypoint: "python3 -m pytest"
    networks:
      - net

    


volumes:
  postgres_data1:

networks:
  net:
    driver: bridge

  

